#!/bin/bash
# script for Mount EFI 
# chris1111 

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"


#############################################################################
DEST_VOL="${3}"
EFI_ROOT_DIR="${DEST_VOL}"/Private/tmp/EFIROOTDIR
install_log="${DEST_VOL}/Private/tmp/Clover_Install_Log.txt"
config_plist_file="${EFI_ROOT_DIR}"/EFI/CLOVER/config.plist
plistbuddy='/usr/libexec/PlistBuddy'

# ---------------------------------------------
# Creating log file
# ---------------------------------------------
echo "" > "$install_log"
echo "Clover EFI installer log - $( date )" >> "$install_log"
echo "Installer version: r5144 (commit: 7b8e78775) EFI bootloader" >> "$install_log"
echo "======================================================" >> "$install_log"
diskutil list >> "$install_log"

echo "====================================================="
echo " "
echo "Don't install any of boot1f32, boot1h and boot1x,"
echo "used for 4kb harddisk with manual install."
echo " "
echo "====================================================="

# Mark that the option was selected
/usr/libexec/PlistBuddy -c "Add $installer_choice bool true" "$CLOVER_INSTALLER_PLIST_NEW" >/dev/null

echo "======================================================" >> "$install_log"
echo "Installing BootSectors/BootLoader" >> "$install_log"
echo "" >> "$install_log"
echo "Stage 0 - Don't write any of boot0af, boot0md, boot0ss to ${DEST_VOL}" >> "$install_log"
echo "Stage 1 - Don't write any of boot1h2, boot1f32alt, boot1xalt to ${DEST_VOL}"      >> "$install_log"



# config.plist
customPlists=$(find "${EFI_ROOT_DIR}"/EFI/CLOVER/OEM -name *.plist | grep -Ev 'SystemProductName')
if [[ ! -f "${EFI_ROOT_DIR}/EFI/CLOVER/config.plist" && "${customPlists}" == "" ]]; then
    cp -fv "${EFI_ROOT_DIR}/EFI/CLOVER/config-sample.plist" "${EFI_ROOT_DIR}/EFI/CLOVER/config.plist"
fi

echo "" >> "${install_log}"

echo "======================================================" >> "${install_log}"
echo "=========== Clover EFI Installation Finish ===========" >> "${install_log}"
echo "======================================================" >> "${install_log}"

# ---------------------------------------------
# Cleanup
# ---------------------------------------------

if [[ -e "$install_log" && -d "${EFI_ROOT_DIR}/EFI" ]]; then
    mv -f "$install_log" "${EFI_ROOT_DIR}/EFI/Clover_Install_Log.txt"
fi

Sleep 2
# Don't keep config-sample.plist
rm -f "${EFI_ROOT_DIR}/EFI/CLOVER/config-sample.plist"
rm -f "${EFI_ROOT_DIR}/EFI/CLOVER/drivers/UEFI/SMCHelper.efi"
rm -f "${EFI_ROOT_DIR}/EFI/CLOVER/drivers/BIOS/SMCHelper.efi"
Sleep 1
# Remove link to the partition that contain the EFI folder
rm -rf "${DEST_VOL}"/Private/tmp/EFIROOTDIR



		