#!/bin/bash

echo "==============================================="
echo "EFIFolder Pre-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"


DEST_VOL="${3}"
EFI_ROOT_DIR="${DEST_VOL}"/Private/tmp/EFIROOTDIR
install_log="${DEST_VOL}/Private/tmp/Clover_Install_Log.txt"
plistbuddy='/usr/libexec/PlistBuddy'

# ---------------------------------------------
# Creating log file
# ---------------------------------------------
echo "" > "$install_log"
echo "Clover EFI installer log - $( date )" >> "$install_log"
echo "Installer version: r5144 (commit: 7b8e78775) EFI bootloader" >> "$install_log"
echo "======================================================" >> "$install_log"
diskutil list >> "$install_log"


mkdir -p "${DEST_VOL}"/Private/tmp
Sleep 2
# ---------------------------------------------
# Mount ESP partition
# ---------------------------------------------

./MountESP "$DEST_VOL" "$EFI_ROOT_DIR"

rm -rf /"$3"/Private/tmp/EFIROOTDIR/EFI/OC
rm -rf /"$3"/Private/tmp/EFIROOTDIR/EFI/BOOT
rm -rf /"$3"/Private/tmp/EFIROOTDIR/EFI/CLOVER
rm -rf /"$3"/Private/tmp/EFIROOTDIR/EFI/Clover_Install_Log.txt
